# alacritty config

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
    ]

[window]
    opacity = 0.65

[font]
    normal = { family = "JetBrains Mono", style = "Regular" }
    size = 16
