# alacritty config

[general]
import = [
    "~/.config/alacritty/themes/themes/pastel_dark.toml"
    ]

[window]
    opacity = 0.8

[font]
    normal = { family = "JetBrains Mono", style = "Regular" }
    size = 14

[env]
    TERM = "xterm-256color"
